### ISSUE TITLE
[Suggestion & Issue] Brightness & Idle timer

### ISSUE THREAD

**Issue by NotDevX** [Stachugit/CatHack#1]
Add options to the settings to edit the Brightness of the screen and to change the timer when it goes to the Idle cat image screen.

Also i found a bug, when going into Infrared and going to TVBegone the screen goes wonky until you restart it

**Comment by Stachugit** [comment]
> Also i found a bug, when going into Infrared and going to TVBegone the screen goes wonky until you restart it

try reflashing the firmware, I have already had reports of this problem and reflash solved the problem
