### ISSUE TITLE
ideas to add to firmware update

### ISSUE THREAD

**Issue by paccbet1337** [Stachugit/CatHack#17]
Hello, your firmware is perfect, but it lacks a couple of functions - support nrf24l01 and ir transmitter, there is also a great idea - to add copying of the key type, that is, you put the key to the display, press the buttons that are put under your key, these buttons have values, numbers, which can then be used to make a copy of the key, which is useful for those who often lose their keys. sorry my english is bad, hope the new update will be the best! Good luck!

**Comment by Stachugit** [comment]
> Hello, your firmware is perfect, but it lacks a couple of functions - support nrf24l01 and ir transmitter, there is also a great idea - to add copying of the key type, that is, you put the key to the display, press the buttons that are put under your key, these buttons have values, numbers, which can then be used to make a copy of the key, which is useful for those who often lose their keys. sorry my english is bad, hope the new update will be the best! Good luck!

Thanks for your suggestions, I will take your ideas into consideration😁
