### ISSUE TITLE
(Stachugit view pls) Parts list for those struggling finding them

### ISSUE THREAD

**Issue by Cattodog** [Stachugit/CatHack#22]
For those of you out there that can find the parts, I have a parts list for you!
6-pin headers:
https://www.digikey.com/en/products/detail/harwin-inc/M50-3930642/7044033
3x7cm prototype board:
https://www.adafruit.com/product/4784?gad_source=1&gbraid=0AAAAADx9JvT7GJycabfkLHJVlrrIpY25M (I use adafruit because I know its high quality)
CC1101 antenna:
https://www.amazon.com/CC1101-Multi-Frequency-Transceiver-Modules-2PCS/dp/B0DBSYK911/ref=asc_df_B0DBSYK911?mcid=df41528c7e6f3fe6aa621c16dc542a85&hvocijid=1530338055683452923-B0DBSYK911-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=721245378154&hvpos=&hvnetw=g&hvrand=1530338055683452923&hvpone=&hvptwo=&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9029000&hvtargid=pla-2281435177658&psc=1
Compact MicroSD:
https://www.newegg.com/p/2A7-00BD-007N6
And Stachugut, could you add links to your items on the “required parts section” so we are guaranteed that the parts work together and both that our issue is a combo of parts. Thank you.

**Comment by Stachugit** [comment]
> For those of you out there that can find the parts, I have a parts list for you!
> 6-pin headers:
> https://www.digikey.com/en/products/detail/harwin-inc/M50-3930642/7044033
> 3x7cm prototype board:
> https://www.adafruit.com/product/4784?gad_source=1&gbraid=0AAAAADx9JvT7GJycabfkLHJVlrrIpY25M (I use adafruit because I know its high quality)
> CC1101 antenna:
> https://www.amazon.com/CC1101-Multi-Frequency-Transceiver-Modules-2PCS/dp/B0DBSYK911/ref=asc_df_B0DBSYK911?mcid=df41528c7e6f3fe6aa621c16dc542a85&hvocijid=1530338055683452923-B0DBSYK911-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=721245378154&hvpos=&hvnetw=g&hvrand=1530338055683452923&hvpone=&hvptwo=&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9029000&hvtargid=pla-2281435177658&psc=1
> Compact MicroSD:
> https://www.newegg.com/p/2A7-00BD-007N6
> And Stachugut, could you add links to your items on the “required parts section” so we are guaranteed that the parts work together and both that our issue is a combo of parts. Thank you.
> 



unfortunately I can't add links to the readme because there were cases where GitHub banned reps with links to AliExpress
